

# This file was *autogenerated* from the file optimization.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0p01 = RealNumber('0.01'); _sage_const_0p99 = RealNumber('0.99'); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6)# Declare variables and assumptions
var('r p y')
assume(r > _sage_const_0 )
assume(p > _sage_const_0 , p < _sage_const_1 )
assume(y > _sage_const_0 , y < _sage_const_1 )

# Define the function
__tmp__=var("r,p,y"); f = symbolic_expression(y*log(p + (_sage_const_1 -p)*r) + (_sage_const_1 -y)*log((_sage_const_1 -p)/r + p)).function(r,p,y)

# First derivative w.r.t. r
df = diff(f, r)

show(df)

# Solve df/dr = 0 for r
sol = solve(df == _sage_const_0 , r)
show(sol)

# plot the function I(y) = f(r, p, y) with r given by sol and p = 0.5
__tmp__=var("y"); r_star = symbolic_expression(sol[_sage_const_0 ]).function(y)

__tmp__=var("y"); f_sub = symbolic_expression(f(r_star(y), _sage_const_1 /_sage_const_2 , y)).function(y)

__tmp__=var("y"); f_sub_num = symbolic_expression(numerical_approx(f_sub(y))).function(y)

plot(f_sub_num(y), _sage_const_0p01 , _sage_const_0p99 , ymin=-_sage_const_5 , ymax=_sage_const_5 , figsize=_sage_const_6 )

